package GUI;

import graph.DirectedGraph;
import graph.Edge;
import graph.Node;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.ubiety.ubigraph.UbigraphClient;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author coc-dell-u14
 */
public class GraphGUI extends javax.swing.JFrame {

    private boolean editingNode;
    private UbigraphClient graph;
    private boolean editingEdge;

    /**
     * Creates new form GraphGUI
     */
    public GraphGUI() {
        editingNode = false;
        editingEdge = false;
        graph = null;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEdges = new javax.swing.JList();
        btnRemoveEdge = new javax.swing.JButton();
        btnNewEdge = new javax.swing.JButton();
        cbxSource = new javax.swing.JComboBox();
        cbxTarget = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSaveEdge = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNodeLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnNodeColor = new javax.swing.JButton();
        btnNewNode = new javax.swing.JButton();
        btnSaveNode = new javax.swing.JButton();
        btnRemoveNode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNodes = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        btnConnect = new javax.swing.JButton();
        btnDraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph Manager");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Edges", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lstEdges.setModel(new DefaultListModel<Edge>()
        );
        lstEdges.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEdges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEdgesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstEdges);

        btnRemoveEdge.setText("Remove Edge");
        btnRemoveEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveEdgeActionPerformed(evt);
            }
        });

        btnNewEdge.setText("New Edge");

        jLabel3.setText("Node Source");

        jLabel4.setText("Node Target");

        btnSaveEdge.setText("Save");
        btnSaveEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEdgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoveEdge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(cbxSource, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(btnNewEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSaveEdge, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveEdge)
                    .addComponent(btnNewEdge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveEdge))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nodes"));

        jLabel1.setText("Node Label:");

        jLabel2.setText("Color:");

        btnNodeColor.setBackground(new java.awt.Color(255, 255, 255));
        btnNodeColor.setText("#FFFFFF");
        btnNodeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNodeColorActionPerformed(evt);
            }
        });

        btnNewNode.setText("New Node");
        btnNewNode.setToolTipText("");
        btnNewNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNodeActionPerformed(evt);
            }
        });

        btnSaveNode.setText("Save Node");
        btnSaveNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNodeActionPerformed(evt);
            }
        });

        btnRemoveNode.setText("Remove Node");
        btnRemoveNode.setToolTipText("");
        btnRemoveNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveNodeActionPerformed(evt);
            }
        });

        lstNodes.setModel(new DefaultListModel<Node>());
        lstNodes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNodes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNodesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstNodes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSaveNode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNodeLabel)
                                .addComponent(btnNodeColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnNewNode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRemoveNode, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveNode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewNode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnNodeColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveNode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ubigraph"));

        btnConnect.setText("Server Disconnected");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnDraw.setText("Draw");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDraw))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNodeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNodeColorActionPerformed
        (new ColorChooser(this, true, btnNodeColor.getBackground())).setVisible(true);
    }//GEN-LAST:event_btnNodeColorActionPerformed

    private void btnNewNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNodeActionPerformed
        newNode();
    }//GEN-LAST:event_btnNewNodeActionPerformed

    private void btnSaveNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNodeActionPerformed
        Node n = new Node(txtNodeLabel.getText(), btnNodeColor.getBackground());
        if (!n.getLabel().isEmpty()) {
            DefaultListModel<Node> s = (DefaultListModel<Node>) lstNodes.getModel();
            if (!s.contains(n)) {
                s.addElement(n);
            } else {
                if (editingNode) {
                    n.setIndex(s.get(s.indexOf(n)).getIndex());
                    s.removeElement(n);
                    s.addElement(n);
                }
            }
            refreshNodesCombos();
            newNode();
        }
    }//GEN-LAST:event_btnSaveNodeActionPerformed

    private void lstNodesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNodesMouseClicked
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Node n = (Node) list.getModel().getElementAt(index);
                txtNodeLabel.setText(n.getLabel());
                btnNodeColor.setText(n.getColor());
                btnNodeColor.setBackground(n.getColorObj());
                editingNode = true;
            }
        } else if (evt.getClickCount() == 3) {   // Triple-click
            int index = list.locationToIndex(evt.getPoint());
        }
    }//GEN-LAST:event_lstNodesMouseClicked

    private void btnRemoveNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveNodeActionPerformed
        DefaultListModel<Node> s = (DefaultListModel<Node>) lstNodes.getModel();
        int i = lstNodes.getSelectedIndex();
        if (i >= 0) {
            DefaultListModel<Edge> edges = (DefaultListModel<Edge>) lstEdges.getModel();
            for (int k = 0; k < edges.getSize(); k++) {
                int j = -1;// = lstEdges.getSelectedIndex();
                Edge e = (Edge) edges.get(k);
                if ((e.getSource().equals(s.get(i))) || (e.getTarget().equals(s.get(i)))) {
                    j = k;
                }
                if (j >= 0) {
                    edges.remove(j);
                }
            }
            s.remove(i);
        }
    }//GEN-LAST:event_btnRemoveNodeActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        try {
            if (graph == null) {
                btnConnect.setText("Server disconnected");
                graph = new UbigraphClient();
            }
            if (graph != null) {
                graph.clear();
                System.out.println("clear:" + graph.clear());;
                btnConnect.setText("Server connected");
            }
        } catch (Exception ex) {
            btnConnect.setText("Server disconnected");
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnSaveEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEdgeActionPerformed
        Edge e = new Edge((Node) cbxSource.getSelectedItem(), (Node) cbxTarget.getSelectedItem());
        if (e.isValid()) {
            DefaultListModel<Edge> s = (DefaultListModel<Edge>) lstEdges.getModel();
            if (!s.contains(e)) {
                s.addElement(e);
            } else {
                if (editingEdge) {
                    e.setIndex(s.get(s.indexOf(e)).getIndex());
                    s.removeElement(e);
                    s.addElement(e);
                }
            }
            newEdge();
        }
    }//GEN-LAST:event_btnSaveEdgeActionPerformed

    private void lstEdgesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEdgesMouseClicked
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Edge e = (Edge) list.getModel().getElementAt(index);
                cbxSource.setSelectedItem(e.getSource());
                cbxTarget.setSelectedItem(e.getTarget());
                editingEdge = true;
            }
        } else if (evt.getClickCount() == 3) {   // Triple-click
            int index = list.locationToIndex(evt.getPoint());
        }
    }//GEN-LAST:event_lstEdgesMouseClicked

    private void btnRemoveEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveEdgeActionPerformed
        DefaultListModel<Edge> s = (DefaultListModel<Edge>) lstEdges.getModel();
        int i = lstEdges.getSelectedIndex();
        if (i >= 0) {
            s.remove(i);
        }
    }//GEN-LAST:event_btnRemoveEdgeActionPerformed

    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        try {
            DirectedGraph dg = new DirectedGraph();
            DefaultListModel<Edge> edges = (DefaultListModel<Edge>) lstEdges.getModel();
            for (int i = 0; i < edges.getSize(); i++) {
                Edge e = edges.get(i);
                dg.addEdge(e);
            }
            DefaultListModel<Node> nodes = (DefaultListModel<Node>) lstNodes.getModel();
            for (int i = 0; i < nodes.getSize(); i++) {
                Node n = nodes.get(i);
                dg.addNode(n);
            }
            dg.writeAt(graph, 0);
        } catch (InterruptedException ex) {
            Logger.getLogger(GraphGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphGUI().setVisible(true);
            }
        });
    }

    public void SetColor(Color color) {
        btnNodeColor.setBackground(color);
        String hex = String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());
        btnNodeColor.setText(hex.toUpperCase());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDraw;
    private javax.swing.JButton btnNewEdge;
    private javax.swing.JButton btnNewNode;
    private javax.swing.JButton btnNodeColor;
    private javax.swing.JButton btnRemoveEdge;
    private javax.swing.JButton btnRemoveNode;
    private javax.swing.JButton btnSaveEdge;
    private javax.swing.JButton btnSaveNode;
    private javax.swing.JComboBox cbxSource;
    private javax.swing.JComboBox cbxTarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstEdges;
    private javax.swing.JList lstNodes;
    private javax.swing.JTextField txtNodeLabel;
    // End of variables declaration//GEN-END:variables

    private void newNode() {
        txtNodeLabel.setText("");
        Color color = Color.WHITE;
        btnNodeColor.setBackground(color);
        String hex;
        hex = "#" + Integer.toHexString(color.getRGB()).substring(2);
        btnNodeColor.setText(hex.toUpperCase());
        editingNode = false;
    }

    private void refreshNodesCombos() {
        DefaultComboBoxModel<Node> source = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<Node> target = new DefaultComboBoxModel<>();
        DefaultListModel<Node> s = (DefaultListModel<Node>) lstNodes.getModel();
        Object[] n = s.toArray();
        for (Object n1 : n) {
            Node node = (Node) n1;
            source.addElement(node);
            target.addElement(node);
        }
        cbxSource.setModel(source);
        cbxTarget.setModel(target);
    }

    private void newEdge() {
        cbxSource.setSelectedIndex(-1);
        cbxTarget.setSelectedIndex(-1);
        editingEdge = false;
    }
}
